export const initialData = {
  boardName: "Sync Board",
  subtitle: "Project Task Management",
  stats: {
    progress: 60,
    completed: 9,
    total: 15,
  },
  team: [
    { name: "Alice Johnson", role: "UI/UX Designer", avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100", status: "online" },
    { name: "Bob Smith", role: "Frontend Developer", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100", status: "online" },
    { name: "Charlie Brown", role: "Backend Developer", avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100", status: "away" },
    { name: "Diana White", role: "QA Tester", avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100", status: "offline" },
  ],
  upcomingDeadlines: [
    { date: "Aug 20", title: "Design Login Page", color: "border-red-500" },
    { date: "Aug 21", title: "API Integration", color: "border-amber-500" },
    { date: "Aug 22", title: "Write Documentation", color: "border-blue-500" },
    { date: "Aug 23", title: "Create Test Cases", color: "border-purple-500" },
    { date: "Aug 24", title: "QA Testing Pass", color: "border-emerald-500" },
  ],
  columns: [
    {
      id: "col-1",
      title: "To Do",
      count: 4,
      bgColor: "bg-blue-50/70 border-blue-100",
      badgeColor: "bg-blue-100 text-blue-700",
      tasks: [
        {
          id: "t1",
          title: "Design Login Page",
          description: "Create UI for user login page according to Figma design.",
          category: "UI/UX",
          categoryColor: "bg-purple-100 text-purple-700",
          priority: "High",
          priorityColor: "bg-red-100 text-red-600",
          dueDate: "Aug 20",
          assignee: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100",
        },
        {
          id: "t2",
          title: "Set Up Database",
          description: "Create and configure the project database.",
          category: "Backend",
          categoryColor: "bg-blue-100 text-blue-700",
          priority: "Medium",
          priorityColor: "bg-amber-100 text-amber-700",
          dueDate: "Aug 21",
          assignee: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100",
        },
        {
          id: "t3",
          title: "Write Documentation",
          description: "Prepare project documentation for the first release.",
          category: "Docs",
          categoryColor: "bg-emerald-100 text-emerald-700",
          priority: "Low",
          priorityColor: "bg-slate-100 text-slate-600",
          dueDate: "Aug 22",
          assignee: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100",
        },
        {
          id: "t4",
          title: "Create Test Cases",
          description: "Write test cases for all main features.",
          category: "Testing",
          categoryColor: "bg-indigo-100 text-indigo-700",
          priority: "Medium",
          priorityColor: "bg-amber-100 text-amber-700",
          dueDate: "Aug 23",
          assignee: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100",
        },
      ],
    },
    {
      id: "col-2",
      title: "In Progress",
      count: 3,
      bgColor: "bg-amber-50/70 border-amber-100",
      badgeColor: "bg-amber-100 text-amber-800",
      tasks: [
        {
          id: "t5",
          title: "Develop Home Page",
          description: "Build responsive home page with featured content.",
          category: "Frontend",
          categoryColor: "bg-sky-100 text-sky-700",
          priority: "High",
          priorityColor: "bg-red-100 text-red-600",
          dueDate: "Aug 20",
          assignee: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100",
        },
        {
          id: "t6",
          title: "API Integration",
          description: "Connect frontend with backend API and test data flow.",
          category: "Backend",
          categoryColor: "bg-blue-100 text-blue-700",
          priority: "High",
          priorityColor: "bg-red-100 text-red-600",
          dueDate: "Aug 21",
          assignee: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100",
        },
        {
          id: "t7",
          title: "UI Testing",
          description: "Test UI components and fix responsive issues.",
          category: "Testing",
          categoryColor: "bg-indigo-100 text-indigo-700",
          priority: "Medium",
          priorityColor: "bg-amber-100 text-amber-700",
          dueDate: "Aug 22",
          assignee: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100",
        },
      ],
    },
    {
      id: "col-3",
      title: "Done",
      count: 5,
      bgColor: "bg-emerald-50/70 border-emerald-100",
      badgeColor: "bg-emerald-100 text-emerald-800",
      tasks: [
        {
          id: "t8",
          title: "Project Setup",
          description: "Initialize project repository and development environment.",
          category: "Setup",
          categoryColor: "bg-emerald-100 text-emerald-700",
          completed: true,
          dueDate: "Aug 15",
          assignee: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100",
        },
        {
          id: "t9",
          title: "Requirements Gathering",
          description: "Collect and analyze project requirements.",
          category: "Research",
          categoryColor: "bg-emerald-100 text-emerald-700",
          completed: true,
          dueDate: "Aug 16",
          assignee: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100",
        },
        {
          id: "t10",
          title: "UI Design Wireframes",
          description: "Create initial wireframes for all main pages.",
          category: "UI/UX",
          categoryColor: "bg-purple-100 text-purple-700",
          completed: true,
          dueDate: "Aug 17",
          assignee: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100",
        },
        {
          id: "t11",
          title: "Style Guide",
          description: "Define design system and UI guidelines.",
          category: "UI/UX",
          categoryColor: "bg-purple-100 text-purple-700",
          completed: true,
          dueDate: "Aug 18",
          assignee: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100",
        },
        {
          id: "t12",
          title: "Initial Development",
          description: "Set up code structure and basic components.",
          category: "Frontend",
          categoryColor: "bg-sky-100 text-sky-700",
          completed: true,
          dueDate: "Aug 18",
          assignee: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100",
        },
      ],
    },
  ],
};
 